version: '3'

services:
  api:
    image: node:18-alpine
    container_name: mkplace-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres
    container_name: mkplace-db
    ports:
      - 5432:5432
    environment:
      # POSTGRES_USER: postgres # Defaults to 'postgres'
      POSTGRES_PASSWORD: secret
